- alias: Prepare the house for bed time
  trigger:
    platform: state
    entity_id: input_boolean.bed_time
    to: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.lights
    - service: homeassistant.turn_off
      data:
        entity_id: group.swiches
    - service: light.turn_on
      data:
        entity_id: light.kitchen_sink_light_switch_level
        brightness_pct: 2
    - service: climate.set_hold_mode
      data: 
        entity_id: climate.Home
        hold_mode: sleep
    - service: remote.turn_off
      data:
        entity_id: remote.living_room, remote.tv_room
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bed_time
