#################################################################
## Kitchen light automations
#################################################################


# Turn off the kitchen lights when motion stops at night
- alias: Kitchen lights - motion stops at night

  trigger:
    - platform: state
      entity_id: group.kitchen_occupancy
      from: 'on'
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: input_boolean.night_mode
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.home_occupancy
      state: 'on'
    - condition: state
      entity_id: input_boolean.quiet_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
    - condition: state
      entity_id: group.kitchen_occupancy
      state: 'off'

  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.kitchen_lights


# Moonlight the kitchen when the lights turn off at night
- alias: Kitchen lights - moonlight kitchen

  trigger: 
    - platform: state
      entity_id: group.kitchen_lights
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: input_boolean.moonlight
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.home_occupancy
      state: 'on'
    - condition: state
      entity_id: input_boolean.quiet_mode
      state: 'off'
    - condition: state
      entity_id: group.kitchen_lights
      state: 'off'
    - condition: state
      entity_id: input_boolean.moonlight
      state: 'on'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
  
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.kitchen_lights_moonlight
        brightness_pct: '10'
        transition: 30
