#################################################################
## Laundry room light automations
#################################################################


# Turn on the laundry room lights when the tracker changes to on
- alias: Laundry room lights - tracker on

  trigger:
    platform: state
    entity_id: input_select.laundry_room_lights_tracker
    to: 'on'

  action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.laundry_room_lights
        brightness_pct: 100


# Turn off the laundry room lights when the tracker changes to off
- alias: Laundry room lights - tracker off

  trigger:
    platform: state
    entity_id: input_select.laundry_room_lights_tracker
    to: 'off'

  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.laundry_room_lights


# Stage the laundry room lights when the tracker changes to stage
- alias: Laundry room lights - tracker stage

  trigger:
    platform: state
    entity_id: input_select.laundry_room_lights_tracker
    to: 'stage'

  action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.laundry_room_lights
        brightness_pct: 20


# Stage the light when there is motion in the bathroom
- alias: Laundry room lights - stage active

  trigger:
    platform: state
    entity_id: group.second_bathroom_occupancy
    to: 'on'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.home_occupancy
        state: 'on'
      - condition: state
        entity_id: input_boolean.quiet_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.laundry_room_lights_tracker
            state: 'off'
          - condition: state
            entity_id: input_select.laundry_room_lights_tracker
            state: 'stage'
  
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.laundry_room_lights_tracker
        option: 'stage'
    - service: logbook.log
      data:
        entity_id: group.laundry_room_lights
        domain: 'automation'
        name: 'laundry room lights: '
        message: 'staged by second bathroom motion'


# Turn tracker to on when there is motion in the laundry room
- alias: Laundry room lights - motion on

  trigger:
    platform: state
    entity_id: group.laundry_room_occupancy
    to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.home_occupancy
      state: 'on'
    - condition: state
      entity_id: input_boolean.quiet_mode
      state: 'off'
    - condition: template
      value_template: "{{ not is_state('input_select.laundry_room_lights_tracker', 'manual') }}"

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.laundry_room_lights_tracker
        option: 'on'
    - service: logbook.log
      data:
        entity_id: group.laundry_room_lights
        domain: 'automation'
        name: 'laundry room lights: '
        message: 'turned on by laundry room motion'        


# Turn tracker to off if laundry room motion stops and tracker state is on
- alias: Laundry room lights - laundry motion off

  trigger:
    platform: state
    entity_id: group.laundry_room_occupancy
    to: 'off'
    for:
      minutes: 10

  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.quiet_mode
    state: 'off'
  - condition: state
    entity_id: input_select.laundry_room_lights_tracker
    state: 'on'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.laundry_room_lights_tracker
        option: 'off'
    - service: logbook.log
      data:
        entity_id: group.laundry_room_lights
        domain: 'automation'
        name: 'laundry room lights: '
        message: 'turned off by laundry room motion'

# Turn tracker to off if second bathroom motion stops and tracker state is stage
- alias: Laundry room lights - bathroom motion off

  trigger:
    platform: state
    entity_id: group.second_bathroom_occupancy
    to: 'off'
    for:
      minutes: 10

  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.quiet_mode
    state: 'off'
  - condition: state
    entity_id: input_select.laundry_room_lights_tracker
    state: 'stage'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.laundry_room_lights_tracker
        option: 'off'
    - service: logbook.log
      data:
        entity_id: group.laundry_room_lights
        domain: 'automation'
        name: 'laundry room lights: '
        message: 'stage turned off by second bathroom motion'

# Turn tracker to off when light turns off
- alias: Laundry room lights - off

  trigger:
    platform: state
    entity_id: group.laundry_room_lights
    to: 'off'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.laundry_room_lights_tracker
        option: 'off'


# Track when light is manually turned on
- alias: Laundry room lights - manual on

  trigger:
    platform: state
    entity_id: group.laundry_room_lights
    to: 'on'

  condition:
    - condition: state
      entity_id: input_select.laundry_room_lights_tracker
      state: 'off'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.laundry_room_lights_tracker
        state: 'manual'
    - service: logbook.log
      data:
        entity_id: group.laundry_room_lights
        domain: 'automation'
        name: 'laundry room lights: '
        message: 'turned on manually'