#################################################################
## Pantry light automations
#################################################################


# Turn on the pantry light when the tracker turns on
- alias: Pantry - tracker on
  
  trigger:
    platform: state
    entity_id: input_select.pantry_lights_tracker
    to: 'on'

  action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.pantry_lights


# Turn off the pantry light when the tracker turns off
- alias: Pantry - tracker off

  trigger:
    platform: state
    entity_id: input_select.pantry_lights_tracker
    to: 'off'

  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.pantry_lights


# Turn the tracker on when the door opens
- alias: Pantry - door open

  trigger:
    platform: state
    entity_id: binary_sensor.pantry_door_sensor
    to: 'on'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.pantry_lights_tracker
        option: 'on'
    - service: logbook.log
      data:
        entity_id: group.pantry_lights
        domain: 'automation'
        name: 'pantry light: '
        message: 'turned on by door sensor'


# Turn the tracker off when the door closes
- alias: Pantry - door closed

  trigger:
    platform: state
    entity_id: binary_sensor.pantry_door_sensor
    to: 'off'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.pantry_lights_tracker
        option: 'off'
    - service: logbook.log
      data:
        entity_id: group.pantry_lights
        domain: 'automation'
        name: 'pantry light: '
        message: 'turned off by door sensor'


# Time out the light if it was turned on by automation
- alias: Pantry - light timeout

  trigger:
    platform: state
    entity_id: input_select.pantry_lights_tracker
    to: 'on'
    for:
      minutes: 90

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.pantry_lights_tracker
        option: 'off'
    - service: logbook.log
      data:
        entity_id: group.pantry_lights
        domain: 'automation'
        name: 'pantry light: '
        message: 'turned off by maximum runtime'


# Turn the tracker off when the light turns off
- alias: Pantry - light off

  trigger:
    platform: state
    entity_id: group.pantry_lights
    to: 'off'
  
  condition:
    - condition: state
      entity_id: input_select.pantry_lights_tracker
      state: 'on'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.pantry_lights_tracker
        option: 'off'
    - service: logbook.log
      data:
        entity_id: group.pantry_lights
        domain: 'automation'
        name: 'pantry light: '
        message: 'turned off manually'        