#################################################################
## Second bathroom light automations
#################################################################

# Turn on the second bathroom light when the tracker is on
- alias: Second bathroom - tracker on

  trigger:
    platform: state
    entity_id: input_boolean.tracker_second_bathroom_light
    from: 'off'
    to: 'on'

  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.second_bathroom_main_lights
    - service: logbook.log
      data:
        entity_id: light.second_bathroom_main_lights
        domain: 'automation'
        name: 'second bathroom light: '
        message: 'turned on by automation'


# Turn on the second bathroom light at reduced level when moonlighting is active
- alias: Second bathroom - tracker moonlight

  trigger:
    - platform: state
      entity_id: input_boolean.moonlight
      from: 'off'
      to: 'on'
    - platform: state
      entityselect
      to: 'off'
      for:
        seconds: 10

  condition:
    - condition: state
      entity_id: light.second_bathroom_main_lights
      state: 'off'
    - condition: state
      entity_id: input_boolean.moonlight
      state: 'on'
    - condition: state
      entity_id: input_select.automation_mode
      state: 'Normal'

  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.second_bathroom_main_lights
        brightness_pct: 2
        transition: 10
    - service: logbook.log
      data:
        entity_id: light.second_bathroom_main_lights
        domain: 'automation'
        name: 'second bathroom light: '
        message: 'moonlit by automation'


# Turn off the second bathroom light when the tracker turns off
- alias: Second bathroom - tracker off

  trigger:
    platform: state
    entity_id: input_boolean.tracker_second_bathroom_light
    from: 'on'
    to: 'off'

  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.second_bathroom_main_lights
    - service: logbook.log
      data:
        entity_id: light.second_bathroom_main_lights
        domain: 'automation'
        name: 'second bathroom light: '
        message: 'turned off by automation'


# Turn the tracker on when motion starts
- alias: Second bathroom - motion starts

  trigger:
    platform: state
    entity_id: group.occupancy_second_bathroom
    from: 'off'
    to: 'on'

  condition:
    - condition: state
      entity_id: input_select.automation_mode
      state: 'Normal'      

  action:
    - service: homeassistant.turn_on
      data:
        entity_id: input_boolean.tracker_second_bathroom_light
        option: 'on'

# Turn the tracker off when motion stops and the tracker is on
- alias: Second bathroom - motion stops

  trigger:
    platform: state
    entity_id: group.occupancy_second_bathroom
    from: 'on'
    to: 'off'
    for:
      minutes: 20

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.tracker_second_bathroom_light
        state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.automation_mode
            state: 'Normal'
          - condition: state
            entity_id: input_select.automation_mode
            state: 'Sleep'
          - condition: state
            entity_id: input_select.automation_mode
            state: 'Away'

  action:
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.tracker_second_bathroom_light


# Turn the tracker off when the light turns off
- alias: Second bathroom - light off

  trigger:
    platform: state
    entity_id: light.second_bathroom_main_lights
    from: 'on'
    to: 'off'

  action:
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.tracker_second_bathroom_light

