#################################################################
## Second bathroom light automations
#################################################################

# Turn on the second bathroom light when the tracker is on
- alias: Second bathroom - tracker on

  trigger:
    platform: state
    entity_id: input_select.second_bathroom_lights_tracker
    to: 'on'

  action:
    - service: input_select.select_option
      data:
        entity_id: group.second_bathroom_lights
        option: 'on'


# Turn off the second bathroom light when the tracker turns off
- alias: Second bathroom - tracker off

  trigger:
    platform: state
    entity_id: input_select.second_bathroom_lights_tracker
    from: 'on'

  action:
    - service: input_select.select_option
      data:
        entity_id: group.second_bathroom_lights
        option: 'off'


# Turn on the second bathroom light at reduced level when moonlighting is active
- alias: Second bathroom - moonlight

  trigger:
    - platform: state
      entity_id: input_boolean.moonlight
      to: 'on'
    - platform: state
      entity_id: input_select.second_bathroom_lights_tracker
      to: 'off'
      for:
        seconds: 10

  condition:
    - condition: state
      entity_id: input_select.second_bathroom_lights_tracker
      state: 'off'
    - condition: state
      entity_id: input_boolean.moonlight
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.home_occupancy
      state: 'on'
    - condition: state
      entity_id: input_boolean.quiet_mode
      state: 'off' 

  action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.second_bathroom_lights
        brightness_pct: 10
        transition: 20
    - service: logbook.log
      data:
        entity_id: group.second_bathroom_lights
        domain: 'automation'
        name: 'second bathroom lights: '
        message: 'moonlit on by automation'


# Turn the tracker on when motion starts
- alias: Second bathroom - motion starts

  trigger:
    platform: state
    entity_id: group.second_bathroom_occupancy
    to: 'on'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.home_occupancy
        state: 'on'
      - condition: state
        entity_id: input_boolean.quiet_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.second_bathroom_lights_tracker
            state: 'off'
          - condition: state
            entity_id: input_select.second_bathroom_lights_tracker
            state: 'stage'       

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.second_bathroom_lights_tracker
        option: 'on'
    - service: logbook.log
      data:
        entity_id: group.second_bathroom_lights
        domain: 'automation'
        name: 'second bathroom lights: '
        message: 'turned on by second bathroom motion'

# Turn the tracker off when motion stops and the tracker is on
- alias: Second bathroom - motion stops

  trigger:
    platform: state
    entity_id: group.second_bathroom_occupancy
    to: 'off'
    for:
      minutes: 20

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.home_occupancy
        state: 'on'
      - condition: state
        entity_id: input_boolean.quiet_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.second_bathroom_lights_tracker
            state: 'on'
          - condition: state
            entity_id: input_select.second_bathroom_lights_tracker
            state: 'stage'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.second_bathroom_lights_tracker
        option: 'off'
    - service: logbook.log
      data:
        entity_id: group.second_bathroom_lights
        domain: 'automation'
        name: 'second bathroom lights: '
        message: 'turned off by second bathroom motion'

# Turn the tracker off when the light turns off
- alias: Second bathroom - light off

  trigger:
    platform: state
    entity_id: group.second_bathroom_lights
    to: 'off'

  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.second_bathroom_lights_tracker
        state: 'on'
      - condition: state
        entity_id: input_select.second_bathroom_lights_tracker
        state: 'stage'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_boolean.second_bathroom_lghts_tracker
        option: 'off'

