#################################################################
## Pantry light automations
#################################################################


# Turn on the utility room light when the tracker turns on
- alias: Utility room - tracker on

  trigger:
    platform: state
    entity_id: input_select.utility_room_lights_tracker
    from: 'off'
    to: 'on'

  action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.utility_room_lights


# Turn off the utility room light when the tracker turns off
- alias: Utility room - tracker off

  trigger:
    platform: state
    entity_id: input_select.utility_room_lights_tracker
    from: 'on'
    to: 'off'

  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.utility_room_lights


# Turn the tracker on when the door opens
- alias: Utility room - door open
  trigger:
    platform: state
    entity_id: binary_sensor.utility_room_door_sensor
    from: 'off'
    to: 'on'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.utility_room_lights_tracker
        option: 'on'
    - service: logbook.log
      data:
        entity_id: group.utility_room_lights
        domain: 'automation'
        name: 'utility room light: '
        message: 'turned on by door sensor'


# Turn the tracker off when the door closes
- alias: Utility room - door closed

  trigger:
    platform: state
    entity_id: binary_sensor.utility_room_door_sensor
    from: 'on'
    to: 'off'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.utility_room_lights_tracker
        option: 'off'
    - service: logbook.log
      data:
        entity_id: group.utility_room_lights
        domain: 'automation'
        name: 'utility room light: '
        message: 'turned off by door sensor'


# Time out the light if it was turned on by automation
- alias: Utility room - light timeout

  trigger:
    platform: state
    entity_id: input_select.utility_room_lights_tracker
    from: 'off'
    to: 'on'
    for:
      minutes: 90

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.utility_room_lights_tracker
        option: 'off'
    - service: logbook.log
      data:
        entity_id: group.utility_room_lights
        domain: 'automation'
        name: 'utility room light: '
        message: 'run time exceeded'


# Turn the tracker off when the light turns off
- alias: Utility room - light off

  trigger:
    platform: state
    entity_id: group.utility_room_lights
    from: 'on'
    to: 'off'

  condition:
    - condition: state
      entity_id: input_select.utility_room_lights_tracker
      state: 'on'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.utility_room_lights_tracker
        option: 'off'
    - service: logbook.log
      data:
        entity_id: group.utility_room_lights
        domain: 'automation'
        name: 'utility room light: '
        message: 'turned off manually'

