- alias: Run tasks when house mode changes to Day
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: 'Day'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.kitchen_sink_light_switch_level
        brightness_pct: 100
    - delay: '00:00:01'
    - service: homeassistant.turn_off
      data:
        entity_id: light.kitchen_sink_light_switch_level
        
